### ISSUE TITLE
Create a 3 row android sqlite DB and content provider

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#101]
the DB should be called 'skills' and the field should be prefix, action, suffix. also make a basic function to add and read content. after this and one more thing I should be ready for alpha 10, the last alpha.

**Comment by victormazevedo** [comment]
Hey buddy! I want to help you and contribute in your project but I have one doubt. Do you need a db called 'skills' with 3 fields called 'prefix', 'action', 'suffix'. Is that right?

**Comment by FultonBrowne** [comment]
yes @victormazevedo  you got it.

**Comment by indracs7** [comment]
Can I take this issue?

**Comment by FultonBrowne** [comment]
yes @indracs97 , thanks.
