### ISSUE TITLE
get rid of black status bar

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#106]
![image](https://user-images.githubusercontent.com/50185337/67441565-35f8ea80-f5b2-11e9-93ef-3526c5ff54cf.png)
have the background image continue to the top

**Comment by harshithpatte** [comment]
I would like to work on it!

**Comment by FultonBrowne** [comment]
Thanks @harshithpatte

**Comment by indracs7** [comment]
Solved this issue 
check PR #109
