### ISSUE TITLE
Add a onResume to mainactivity.java

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#113]
resume list and list position, this is mainly for folding devices.

**Comment by hmuhammadazeem** [comment]
Hey, can you elaborate what should onResume perform? I want to work on it.

**Comment by FultonBrowne** [comment]
well, it needs to keep the list progress and the drawer selection from changing on closing or changing the activity.

**Comment by hmuhammadazeem** [comment]
Can you specify exactly which list? It would help avoid any confusions.
