### ISSUE TITLE
App doesn't load

### ISSUE THREAD

**Issue by airon90** [FultonBrowne/Ara-android#166]
I'm using a Wiko View 2 Go phone with Android 8.1 and latest Ara version from Google Play. I load the app, the splash screen is shown but then the app crashes. How can I help you more in detecting what it doesn't work?

**Comment by FultonBrowne** [comment]
@airon90 can you get the logcat, I know my app works on an s5 with 6.0, on pixles, and oneplus 7pros

**Comment by airon90** [comment]
[adb.txt](https://github.com/FultonBrowne/Ara-android/files/4085794/adb.txt)

I never used adb. I hope it could be useful. Tell me more if you need more info! :)

**Comment by FultonBrowne** [comment]
@airon90 could I see what version of ara your running

**Comment by FultonBrowne** [comment]
@airon90  try granting ara calendar permissions, the next version will not require it.

**Comment by airon90** [comment]
v 1.0beta6 from Google Play Store (waiting for F-Droid one #155) and calendar permission is already given. Even if I delete all data and cache from Ara and set again every permission, nothing changes. [This](https://github.com/FultonBrowne/Ara-android/files/4090696/adb.txt) is the new logcat.

**Comment by FultonBrowne** [comment]
@airon90 I cant seem to figure it out, I've tried reinstalling the app on my phone and on 2 simulators and it works fine, I will do a deeper investigation

**Comment by airon90** [comment]
I succeeded in sending a s.c. feedback, after last crash. I hope it would be more useful

**Comment by FultonBrowne** [comment]
@airon90 I may have found the issue, it appears to isolated to android 8.1 and will be patched today and there will be an update tomorrow or the day after.

**Comment by FultonBrowne** [comment]
@airon90 it should be fixed

**Comment by airon90** [comment]
It is. Thank you very much!
