### ISSUE TITLE
Choose a translation platform

### ISSUE THREAD

**Issue by airon90** [FultonBrowne/Ara-android#175]
Even if the app is in beta stage yet, one could prefer to have its app localized. In order to organize the translations properly, I suggest to use a translation platform, e.g. Crowdin or Transifex. Translators will be automatically advised abiut new strings or changed strings, instead of constantly looking for them through the source code and history

**Comment by FultonBrowne** [comment]
Thanks @airon90 I just started using crowdin and you should start seeing more translations soon!

**Comment by FultonBrowne** [comment]
I had some issues with the service I chose. reopening now.
