### ISSUE TITLE
settings page 

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#60]
get the settings page in working order. and add setting for theme, notifications, hey ara support, and account settings.

**Comment by alistairholmes** [comment]
Hi there:wave: Would you like some assistance with your settings page? Not exactly sure what you mean by getting it in working order.

**Comment by FultonBrowne** [comment]
Well everything is static and the theming is in disarray.

**Comment by FultonBrowne** [comment]
In the settings there are several settings we are looking at:
* themes, use the android 10 theme thing to switch between dark and light mode
* display name, what  you want ara to call you
* a list of accounts, just a basic list for now
* notifications on or off, I will be adding some notification functionality this week

**Comment by FultonBrowne** [comment]
The theming is about done, thank you @snufflesrea!
