### ISSUE TITLE
Grid view on certian width

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#64]
This could be nice for folding devices, external displays, and tablets. when the screen hits a certain width, change the layout manager in the recycle view (MainActivity.java) from a linear mode to a grid mode, if a certain width is reached.

**Comment by mayokunadeniyi** [comment]
Hello, I'll love to work on this

**Comment by FultonBrowne** [comment]
Thank you @mayokunthefirst !
