### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#80]
I would love a worldwide release, There is English and Spanish, but German would be great too. Also any other language is welcome, so feel free to contribute.

**Comment by Meeze** [comment]
Hey I would like to help you, can you tell me where the messages/files that I should translate are?

**Comment by root-ansh** [comment]
I would like to work on this issue

**Comment by FultonBrowne** [comment]
thank you @root-ansh

**Comment by Idrinth** [comment]
while @root-ansh did a good job, it*s not quite there yet, something along the lines of 1/3 done. maybe reopen this issue, @FultonBrowne ?

**Comment by FultonBrowne** [comment]
Thank you @Idrinth, I have reopened the issue.
