### ISSUE TITLE
Dutch and French translation 

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#84]
a international release is very important to me, so the more languages the better.

**Comment by wouterdedroog** [comment]
I'd be willing to contribute, is it possible to start translating?

**Comment by FultonBrowne** [comment]
@MrWouterNL, Are you familiar with android app translation?

**Comment by wouterdedroog** [comment]
Nope, this will be a first, but I'm willing to put in some effort.

**Comment by FultonBrowne** [comment]
I can create the files to support the translations, what language do you want to do?

**Comment by wouterdedroog** [comment]
Dutch (nl_NL)

**Comment by FultonBrowne** [comment]
are you running android studio or intellij?

**Comment by wouterdedroog** [comment]
Android studio

**Comment by FultonBrowne** [comment]
Ok, so open up ara in android studio go to the dutch string.xml file, then you will see an option for a translation editor, open that, you will see a dutch row, edit the text in there. note DON'T EDIT THE KEYS
![image](https://user-images.githubusercontent.com/50185337/66783595-1284c000-ee8d-11e9-935d-10eb833f7a4e.png)

**Comment by wachiranduati** [comment]
ignoring the highlighted Dutch and French title and going with the more languages the better....;) would you mind me adding swahili to the languages?

**Comment by FultonBrowne** [comment]
@wachiranduati , sure that works.

**Comment by siddlal** [comment]
Hi @FultonBrowne, If its possible  can I add german to the languages ?

**Comment by FultonBrowne** [comment]
Yes @siddlal that would be great.

**Comment by jhaumont** [comment]
Hello @FultonBrowne, I can work on french translation

**Comment by FultonBrowne** [comment]
sure @jhaumont that would be great, thanks.

**Comment by wouterdedroog** [comment]
Is translation of the large_text string necessary? It appears to be a copy pasta for testing purposes.

**Comment by FultonBrowne** [comment]
its not @MrWouterNL , thanks for asking.
