### ISSUE TITLE
clean up voicemain.java

### ISSUE THREAD

**Issue by FultonBrowne** [FultonBrowne/Ara-android#95]
move functions to new files in util folder, just to help keep code neat and readable.

**Comment by dibyanshuanand** [comment]
I would like to help ... can I start working on it ?

**Comment by FultonBrowne** [comment]
yes @dibyanshuanand , go ahead. Thanks for contributing!

**Comment by dibyanshuanand** [comment]
The code changes are leading to additional bugs which I cannot resolve .. so anyone else can take up the issue @FultonBrowne

**Comment by FultonBrowne** [comment]
Thanks @dibyanshuanand, maybe watch and star the repo get notified about contributing opportunity's
